[package]
name = "language"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cry_script = { path = "crates/cry_script" }
utils = { path = "crates/utils" }
sysinfo = "*"
