[package]
name = "cry_script"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# or "z"
opt-level = "s"

[dependencies]
colored = "*"
rand = "0.8.5"